### ISSUE TITLE
Is using the Roon API directly in a web browser still supported?

### ISSUE THREAD

**Issue by MattTW** [RoonLabs/node-roon-api#11]
I followed the directions at the bottom of the README and also tried the example web app project.   On my Mac with Safari/Chrome it errors out and I am not sure why.  I am pretty confident I have the host set appropriately to point to my Roon server - it isn't localhost from the browser's point of view, but a machine on my local network.     Should it still be working?  If so, I can post more details about the issue.

Thanks,
Matt

**Comment by bcoburn3** [comment]
It should still work.  I believe the problem is that we updated the main API library in a way that meant the example web app project also needed to be changed slightly, and then forgot to update the example project.

Can you try again with the current most recent version of https://github.com/RoonLabs/roon-extension-web-testapp/blob/master/app.js ?  commit is d451f03, it should be fixed now.

Generally we plan on continuing to support using the API directly in a web browser.

**Comment by MattTW** [comment]
Got it working.   Thank you!
