### ISSUE TITLE
Does other language API support?

### ISSUE THREAD

**Issue by fengjiannan2010** [RoonLabs/node-roon-api#21]
I am doing a RemoteControl project using qt+qml,
Is there any corresponding api support, or .net core api?

**Comment by dannyfiresnake** [comment]
Nope, but you can easily build a new SDK using the techniques of the node SDK.

**Comment by sbosley** [comment]
I too was looking for the API in other languages a while back, and when I couldn't find any, I wrote an [extension](https://github.com/sbosley/roon-api-grpc-bridge) to wrap the node SDK using gRPC, so that much of the API surface could be called using a generated client library for a number of languages. Would Roon ever consider adopting a protocol like gRPC for the API instead of a single-language SDK? I'd love to be able to use something more language-agnostic without resorting to my hacky extension :)
