### ISSUE TITLE
Zones with more than one output device not shoen in zone dropdown of extensions

### ISSUE THREAD

**Issue by DrCWO** [RoonLabs/node-roon-api#25]
I stuck with one Problem.
In one of the images attached you see my roon setup combining two output devices to one zone.
The transport.subscribe_zones API function also delivers the correct setup, also attached.

Now I have programmed a roon extension using the zone dropdown:
        l.layout.push({
            type: "zone",
            title: "Zone",
            setting: "zone",
        });
In this dropdown only the individual output devices got listed instead of the zones I expected (see attached image)
Is tis an error in the API or have I missed something?

This request is a bit urgent because one of my customers of rooDial complains.

![roon_output](https://user-images.githubusercontent.com/65152014/103867336-75342e00-50c7-11eb-9ab8-03774eb16388.png)
[transport.subscribe_zones.txt](https://github.com/RoonLabs/node-roon-api/files/5780303/transport.subscribe_zones.txt)
![zones_dropdown](https://user-images.githubusercontent.com/65152014/103867364-7ebd9600-50c7-11eb-86dd-8d69e7239fc4.png)

**Comment by blucz** [comment]
You haven't missed anything--that is how it is supposed to work. I think the naming in the settings API is a little bit inconsistent. What it is calling a "zone" is called an "output" in the transport API. If we bound extension behavior like this to zones, the extension would effectively come and go as zones are grouped and ungrouped. We judged that that was not going to provide a good experience, and that is why it is this way. 

There is no way to get a list of zones in settings, just the individual outputs. The idea is, you are going to tie the extension's behavior to a particular audio device and then the extension will automatically work with whichever group that is a part of, even as the output moves from group to group. 

The user would set up your extension so that the Surface Dial is bound to the output in the same room as the knob. And then if they choose to group it later, the knob will apply to the whole group, "following around" the audio device that it is placed near.

**Comment by DrCWO** [comment]
Brian, 

thanks for your lines.

Meanwhile I understood that some of the methods in the transport API accept output_id , and some zone_id + output_id.

 

I decides to dropped the “zone” type and make my own dropdown with real zones! At luck subscribe_zones provides the 

zones and all changes to them so I can hold a consistent mirror image of all zones with all their outputs within rooDial. 

Users can now select a grouped zone and change volume for all the attached outputs. 

For this I have to call the change_volume several times, once for each output but who cares ;-) I will publish it soon.

 

Please allow me two more question:

1.	In a grouped zone with multiple outputs I see in the right lower corner right above the speaker symbol a “+” and a “-“ that affects all outputs.
Also a “Mute All” is in this line. Is there a chance to access these functions via transport API? I could not find a method for that.
2.	This “+” and “-“ buttons I can also see if the Deep Harmony plugin is loaded. In this case the “+” and “-“ fires infrared as long as the “+” and “-“ got pressed down.
I also did not make it to access these by transport API. Any idea or “hidden” feature?

 



 

Thanks 

Charly

 

 

Von: Brian Luczkiewicz <notifications@github.com> 
Gesendet: Freitag, 8. Januar 2021 02:49
An: RoonLabs/node-roon-api <node-roon-api@noreply.github.com>
Cc: DrCWO <info@definiteaudio.de>; Author <author@noreply.github.com>
Betreff: Re: [RoonLabs/node-roon-api] Zones with more than one output device not shoen in zone dropdown of extensions (#25)

 

You haven't missed anything--that is how it is supposed to work. I think the naming in the settings API is a little bit inconsistent. What it is calling a "zone" is called an "output" in the transport API. If we bound extension behavior like this to zones, the extension would effectively come and go as zones are grouped and ungrouped. We judged that that was not going to provide a good experience, and that is why it is this way.

There is no way to get a list of zones in settings, just the individual outputs. The idea is, you are going to tie the extension's behavior to a particular audio device and then the extension will automatically work with whichever group that is a part of, even as the output moves from group to group.

The user would set up your extension so that the Surface Dial is bound to the output in the same room as the knob. And then if they choose to group it later, the knob will apply to the whole group, "following around" the audio device that it is placed near.

**Comment by blucz** [comment]
There is a `mute_all` command in the transport API. 

We do not plan to let extensions discover other extensions.
